### ISSUE TITLE
Add test program(s) to the/a Makefile

### ISSUE THREAD

**Issue by msoucy** [rossdylan/libfab#13]
Since you already have the makefile, add the test program to it. Ideally, this would involve splitting the single program into a bunch of test programs as well.

**Comment by rossdylan** [comment]
I'm planning on writing a series of proper unit tests for libfab so I can then hook it into travis-ci. Thinking about using [CUnit](http://cunit.sourceforge.net/) as the testing framework. I'll probably start work on this in a new branch feature/tests this week.

**Comment by rossdylan** [comment]
Done as of 2b45f26f3fc8d2f4be683ac6b46c6a738a8d0654
