### ISSUE TITLE
xterm_to_rgb publicity

### ISSUE THREAD

**Issue by msoucy** [rossdylan/libfab#8]
`xterm_to_rgb` seems like an awesome tool to have available for the end user - is should also take `unsigned char`, since by definition it handles exactly 256 values.

**Comment by ryansb** [comment]
I'm in favor of having it public, I was going to expose it in tremendous (along with a version that takes a hexadecimal color).

**Comment by rossdylan** [comment]
Cool since both of you want to include this in bindings I'll expose it publicly..
